// <auto-generated />
using System;
using IronMaidenRegistry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronMaidenRegistry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231229151032_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InstrumentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("InstrumentName");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IDX_Id_Instrument");

                    b.ToTable("Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2d4d6b0-dace-47bb-86bd-418d9eec8698"),
                            Name = "Bass"
                        },
                        new
                        {
                            Id = new Guid("84a3b081-db74-4d81-8222-f0216ecb9d5a"),
                            Name = "Drum"
                        },
                        new
                        {
                            Id = new Guid("9686af26-782e-41f7-9daa-5f79abc5b2c4"),
                            Name = "Guitar"
                        },
                        new
                        {
                            Id = new Guid("09449193-e9aa-4107-b92f-b1cfc027ebea"),
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = new Guid("2c11b548-e70d-4b0d-9a1c-31daa5c9928a"),
                            Name = "Vocals"
                        });
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MemberId");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("DATE")
                        .HasColumnName("BirthDate");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("FullName");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IDX_Id_Member");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0cba1ca5-7d18-46d3-ad99-1fdfa040359f"),
                            BirthDate = new DateOnly(1957, 2, 27),
                            FullName = "Adrian Smith",
                            InstrumentId = new Guid("9686af26-782e-41f7-9daa-5f79abc5b2c4")
                        },
                        new
                        {
                            Id = new Guid("ebc53600-98d8-49d7-bba3-8581f840efbb"),
                            BirthDate = new DateOnly(1963, 5, 29),
                            FullName = "Blaze Bayley",
                            InstrumentId = new Guid("2c11b548-e70d-4b0d-9a1c-31daa5c9928a")
                        },
                        new
                        {
                            Id = new Guid("21665fb0-1264-4c90-85b9-b2c16d8b80c7"),
                            BirthDate = new DateOnly(1958, 8, 7),
                            FullName = "Bruce Dickson",
                            InstrumentId = new Guid("2c11b548-e70d-4b0d-9a1c-31daa5c9928a")
                        },
                        new
                        {
                            Id = new Guid("3ffac757-df7b-450b-a978-2b0c9d049826"),
                            BirthDate = new DateOnly(1957, 3, 7),
                            FullName = "Clive Burr",
                            InstrumentId = new Guid("84a3b081-db74-4d81-8222-f0216ecb9d5a")
                        },
                        new
                        {
                            Id = new Guid("9c451aba-c010-4b11-97ee-dc802855cd8b"),
                            BirthDate = new DateOnly(1956, 12, 23),
                            FullName = "Dave Murray",
                            InstrumentId = new Guid("9686af26-782e-41f7-9daa-5f79abc5b2c4")
                        },
                        new
                        {
                            Id = new Guid("1f5af4a7-b538-4dd4-af0d-38287047e70a"),
                            BirthDate = new DateOnly(1952, 9, 27),
                            FullName = "Denis Stratton",
                            InstrumentId = new Guid("9686af26-782e-41f7-9daa-5f79abc5b2c4")
                        },
                        new
                        {
                            Id = new Guid("9b9a8d08-c432-40f2-bc1f-dc7196bc2b1e"),
                            BirthDate = new DateOnly(1957, 1, 27),
                            FullName = "Janick Gers",
                            InstrumentId = new Guid("9686af26-782e-41f7-9daa-5f79abc5b2c4")
                        },
                        new
                        {
                            Id = new Guid("bb582f22-30a1-444d-928e-db64916d01b1"),
                            BirthDate = new DateOnly(1952, 6, 5),
                            FullName = "Nicko McBrain",
                            InstrumentId = new Guid("84a3b081-db74-4d81-8222-f0216ecb9d5a")
                        },
                        new
                        {
                            Id = new Guid("6a259e55-d4b1-4709-af90-e6e80f756b6f"),
                            BirthDate = new DateOnly(1958, 5, 17),
                            FullName = "Paul Di'Anno",
                            InstrumentId = new Guid("2c11b548-e70d-4b0d-9a1c-31daa5c9928a")
                        },
                        new
                        {
                            Id = new Guid("914b1048-f961-4169-b4dc-5b2ace57e9d8"),
                            BirthDate = new DateOnly(1956, 3, 12),
                            FullName = "Steve Harris",
                            InstrumentId = new Guid("d2d4d6b0-dace-47bb-86bd-418d9eec8698")
                        });
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.MemberSong", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MemberId", "SongId");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("IDX_MemberId_MembersSongs");

                    b.HasIndex("SongId")
                        .HasDatabaseName("IDX_SongId_MembersSongs");

                    b.ToTable("MembersSongs", (string)null);

                    b.HasData(
                        new
                        {
                            MemberId = new Guid("21665fb0-1264-4c90-85b9-b2c16d8b80c7"),
                            SongId = new Guid("74959ea2-f8ff-4204-979e-bd0ce3fb392a")
                        });
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SongId");

                    b.Property<byte>("AverageScore")
                        .HasColumnType("TINYINT")
                        .HasColumnName("AverageScore");

                    b.Property<byte>("DurationInMinutes")
                        .HasColumnType("TINYINT")
                        .HasColumnName("DurationInMinutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("SongName");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IDX_Id_Song");

                    b.ToTable("Songs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1331b45-f0a8-4bb3-9915-6d44f95e4f0b"),
                            AverageScore = (byte)4,
                            DurationInMinutes = (byte)9,
                            Name = "For the Greater Good of God"
                        },
                        new
                        {
                            Id = new Guid("74959ea2-f8ff-4204-979e-bd0ce3fb392a"),
                            AverageScore = (byte)4,
                            DurationInMinutes = (byte)7,
                            Name = "Fear of the Dark"
                        },
                        new
                        {
                            Id = new Guid("a91ec616-14d5-4712-8255-3e3d00d89f53"),
                            AverageScore = (byte)5,
                            DurationInMinutes = (byte)4,
                            Name = "Prowler"
                        },
                        new
                        {
                            Id = new Guid("0b40c8f5-44d6-48e0-9448-83dbed39ea3c"),
                            AverageScore = (byte)5,
                            DurationInMinutes = (byte)4,
                            Name = "The Trooper"
                        });
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Member", b =>
                {
                    b.HasOne("IronMaidenRegistry.Domain.Entities.Instrument", "Instrument")
                        .WithMany("Members")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.MemberSong", b =>
                {
                    b.HasOne("IronMaidenRegistry.Domain.Entities.Member", "Member")
                        .WithMany("MembersSongs")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronMaidenRegistry.Domain.Entities.Song", "Song")
                        .WithMany("MembersSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Instrument", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Member", b =>
                {
                    b.Navigation("MembersSongs");
                });

            modelBuilder.Entity("IronMaidenRegistry.Domain.Entities.Song", b =>
                {
                    b.Navigation("MembersSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
